version: '0.2'
language: en
allowCompoundWords: true
caseSensitive: false
ignoreRandomStrings: true
words:
  - nums
  - nargs
  - noshiro
  - syncflow
  - testw
  - tscw
ignorePaths:
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - dist/**
  - docs/**
  - agents/common/**
