name: Style Check

on:
  push:
    branches-ignore:
      - 'develop'
      - 'develop*'
    paths-ignore:
      - '**.png'
      - '**.jpg'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  style-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: true
      matrix:
        command:
          - fmt:full
          - md
          - cspell
          - ws:doc
          - ws:check:ext

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Fetch main
        run: git fetch origin main

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        id: setup_node_id
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build synstate
        run: pnpm run ws:build

      - name: Run "${{ matrix.command }}"
        run: pnpm run ${{ matrix.command }}

      - name: Check if there is no file diff
        run: pnpm exec assert-repo-is-clean
