name: Test Coverage

on:
  push:
    branches-ignore:
      - 'develop'
      - 'develop*'
    paths-ignore:
      - '.gitignore'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Fetch main
        run: git fetch origin main

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        id: setup_node_id
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # NOTE: To include this workflow in the branch protection rule status check,
      # skip each steps instead of skipping the entire workflow with paths-ignore.
      - name: Check diff
        id: check_diff_type
        run: pnpm exec check-should-run-type-checks

      - name: Build all packages
        run: pnpm run ws:build

      - name: Run "ws:test:cov" for coverage report
        if: steps.check_diff_type.outputs.should_run == 'true'
        run: pnpm run ws:test:cov

      - name: Check if there is no file diff
        run: pnpm exec assert-repo-is-clean

      - name: Upload coverage reports to Codecov
        if: steps.check_diff_type.outputs.should_run == 'true'
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./app/coverage/coverage-final.json
          flags: app
